# Generated by Django 5.1.1 on 2024-09-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_table',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='user_table',
            old_name='place',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='share_group_table',
            name='CODE',
        ),
        migrations.RemoveField(
            model_name='share_table',
            name='CODE',
        ),
        migrations.AddField(
            model_name='group_members_table',
            name='type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group_table',
            name='Admin',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share_group_table',
            name='topic',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share_table',
            name='topic',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_table',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='complaint_table',
        ),
        migrations.AddField(
            model_name='share_group_table',
            name='code',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share_table',
            name='code',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
