# Generated by Django 5.1.1 on 2024-09-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_image_group_table_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='photo',
        ),
    ]
