# Generated by Django 5.1.1 on 2024-09-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_table_address_remove_user_table_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_table',
            name='rating',
            field=models.IntegerField(default='0'),
        ),
    ]
