# Generated by Django 5.1.1 on 2024-09-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feedback_table_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_table',
            name='feedback',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
