# Generated by Django 5.1.1 on 2024-09-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_feedback_table_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_table',
            name='feedback',
            field=models.CharField(default='ok', max_length=1000),
        ),
    ]
