# Generated by Django 5.1.1 on 2024-09-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_feedback_table_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_table',
            name='age',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_table',
            name='gender',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_table',
            name='phone',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_table',
            name='photo',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback_table',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
