# Generated by Django 5.1.1 on 2024-09-20 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_table_address_user_table_age_user_table_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_table',
            name='replay',
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('replay', models.CharField(max_length=1000)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
            ],
        ),
    ]
