# Generated by Django 5.1.1 on 2024-09-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_feedback_table_replay_complaint_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_table',
            name='code',
            field=models.CharField(max_length=10000),
        ),
    ]
