# Generated by Django 5.1.1 on 2024-09-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_code_table_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_table',
            old_name='Admin',
            new_name='grpName',
        ),
        migrations.RemoveField(
            model_name='group_table',
            name='Name',
        ),
    ]
