# Generated by Django 5.1.1 on 2024-09-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_admin_group_table_grpname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_table',
            name='replay',
        ),
        migrations.AddField(
            model_name='complaint_table',
            name='reply',
            field=models.CharField(default='pending', max_length=1000),
        ),
        migrations.AlterField(
            model_name='feedback_table',
            name='feedback',
            field=models.CharField(max_length=1000),
        ),
    ]
