# Generated by Django 5.1.1 on 2024-09-25 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_complaint_table_replay_complaint_table_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='share_group_table',
            name='USER',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app.user_table'),
            preserve_default=False,
        ),
    ]
