# Generated by Django 5.1.4 on 2024-12-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_share_group_table_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='share_group_table',
            name='Language',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share_table',
            name='Language',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
