# Generated by Django 5.1.4 on 2024-12-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_share_group_table_language_share_table_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code_table',
            old_name='Language',
            new_name='language',
        ),
        migrations.AlterField(
            model_name='code_table',
            name='code',
            field=models.TextField(),
        ),
    ]
