# Generated by Django 5.1.4 on 2024-12-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_language_code_table_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_table',
            name='type',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
