# Generated by Django 5.1.4 on 2024-12-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_code_table_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share_table',
            name='USER',
        ),
        migrations.AddField(
            model_name='share_group_table',
            name='type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share_table',
            name='FROMUSER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to='app.user_table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share_table',
            name='TOUSER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='touser', to='app.user_table'),
            preserve_default=False,
        ),
    ]
