# Generated by Django 5.1.4 on 2024-12-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_share_table_user_share_group_table_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code_table',
            name='type',
        ),
    ]
